### ISSUE TITLE
36C3

### ISSUE THREAD

**Issue by miko007** [maschinendeck/kanban#1]
### Tasks
- [x] Packliste kontrollieren
- [x] Assembly anmelden
- [ ] Infomaterial erstellen
- [ ] Infomaterial produzieren lassen
- [x] Heliumballon klären

### Einpacken
- [ ] Luftsofas
- [x] Schreibtischlampen *(3 Stück)*
- [ ] Wolldecken
- [ ] DECT Telefone
- [ ] Akkuschrauber
- [ ] Bits
- [ ] Bohrmaschine *(klein)*
- [ ] Klammern für Molton 
- [ ] Festplatten Raspberry Pis *(2 Stück)*
- [ ] Gaffertape *(a ton of)*
- [ ] Kabelbinder *(groß & klein)*
- [ ] Lankabel *(a shit ton of)*
- [ ] Crimpzeug *(für RJ45)*
- [x] Heißklebepistole 
- [x] Heißklebesticks
- [ ] Heißluftföhn
- [x] Banner
- [ ] Sticker
- [x] 3D Drucker *(Prusa)*

#### Team Koeter
- [ ] Kabel
- [ ] Lampen
- [ ] Stative
- [ ] Rollbrett
- [ ] Lacktische
- [ ] POE Switch
- [ ] Accesspoint

#### Team MikO
- [x] Beamer
- [x] Switch
- [x] Filament
- [x] Mehrfachsteckdosen
- [ ] Tastatur
- [ ] Mäuse *(IT)*
- [ ] Kleiner Laser
- [ ] Lötzeug
- [ ] evtl Schreibmaschine
- [ ] Ballongas – Transport bis Halle

### Teilnehmer
* MikO | @miko007 
* Dippel
* Koeter
* Icephoenix | @Eisfoehniks 
* Michael
* Zen
* Don Clemente | @DonClemente 
* Suboptimal

### Fahrgemeinschaften
* @DonClemente  *(keine Mitfahrer möglich)*
* Koeter *(+1)* – @Eisfoehniks 
* Dippel *(+1)* – @miko007 

### Beschreibung
Der Maschinendeck Trier e.V. unterhält auf dem diesjährigen **Chaos Communication Congress**  *(36C3)* wieder eine Assembly. In diesem Jahr sogar mit einem kleinen Aufbau. Sie wird Chaos West angegliedert.

Des Weiteren soll es einen Lötworkshop mit Maschinendeck Badges geben.

*(zur Kenntnis: @maschinendeck/redakteure )*
