### ISSUE TITLE
Elektronikautomat

### ISSUE THREAD

**Issue by miko007** [maschinendeck/kanban#2]
### Beschreibung
Ein Zigarettenautomat soll umgebaut werden, so dass er Schachteln mit Elektronikartikeln ausgibt.

[Repository](https://github.com/maschinendeck/Elektronikautomat)

### Tasks
- [x] Projekt im Wiki anlegen
- [x] Projektleiter festlegen
- [x] Automat kaufen
- [x] Automat zum Laufen bringen
- [ ] Möglichkeit zur Schachtelfabrikation erarbeiten
- [ ] Schachteldesign erstellen | @miko007 
- [x] Schachteln anfertigen
- [ ] Designs für Schachtbeschreibung erstellen
- [x] Schlösser reparieren/Automat absperrbar machen
- [ ] PayPal-Integration
- [ ] Automat aufhübschen

Das Budget wurde auf **`0,00€`** festgelegt.

**Comment by miko007** [comment]
test

**Comment by operator2010** [comment]
@miko007 Wie groß soll das Schachtel-Endformat in XxYxZmm werden? Und wie viele Slots (Varianten) mit was für Inhalten gibts?

**Comment by Eisfoehniks** [comment]
Wir haben schon ein paar genauere Informationen in unserem Wiki gesammelt (https://wiki.maschinendeck.org/wiki/Zigarettenautomat). Aktuell steht das Projekt still, da aus Coronagründen ohnehin keine Leute da sind, welche den Automaten verwenden könnten.

**Comment by Eisfoehniks** [comment]
Aktuell wird an einer Backup Batterielösung gearbeitet, damit der automat funktioniert wenn er keinen strom hat.

**Comment by Eisfoehniks** [comment]
Der Automat funktioniert und ist verwendbar, es stehen noch kleinere Upgrades und die optische Verschönerung aus

**Comment by Eisfoehniks** [comment]
Repository mit Firmware, Hardware und Coverbildern hinzugefügt
