### ISSUE TITLE
GlaDOS Deckenleuchte fürs Deck

### ISSUE THREAD

**Issue by miko007** [maschinendeck/kanban#3]
### Beschreibung
Im Hauptraum, wo aktuell der "Kronleuchter" montiert ist, von dem bereits in einem Plenum beschlossen wurde dass er uns verlässt, wäre der ideale Platz, um eine Miniatur von GlaDOS anzubringen.

GlaDOS sieht nicht nur gut aus, sondern backt auch hervorragend saftigen Kuchen und ist vertrauenswürdig im Umgang mit dem Zentralschalter für die Nervengifteinspritzung.

Eine spätere Verbindung zu einem "smarten Assistenten" *(open source, selbsverständlich)* wäre denkbar.

### Weblinks
* [Projektseite][glados]

### Tasks
- [ ] Projekt im Wiki anlegen
- [x] Projektleiter festlegen
- [ ] 3D Teile ausdrucken
- [ ] 3D Teile Nacharbeiten
- [ ] Servos besorgen
- [ ] LEDs besorgen
- [ ] Elektronik verkabeln
- [ ] Mikrocontroller programmieren
- [ ] GlaDOS an die Decke anbringen
- [ ] *There will be Cake*

Das Budget wurde auf **`0,00€`** festgelegt. *(geschätzt auf `50,00€`)*

Ich suche mindestens **`2`** Mitstreiter.

### Bilder
![](http://ytec3d.com/wp-content/gallery/glados-overview/P1030094.JPG)

### Team
* @Eisfoehniks 
* @Vi-ger
* @rekna 
* @YoungCatMike 

[glados]: http://ytec3d.com/glados-lamp/

**Comment by Eisfoehniks** [comment]
Ich habe aktuell keine Zeit für ein weiteres Projekt, finde die Idee aber gut und würde eventuell beim Löten helfen wenn Bedarf besteht. Außerdem hab ich noch ne Hand voll von diesen Kühlplatinen für 1W LEDs, evt. auch einige 1W LEDs und passende Treiber, die ich dem Projekt spenden könnte.

**Comment by Vi-ger** [comment]
Ob ich eine wirkliche Hilfe bin, wage ich zu bezweifeln. Aber ich bin gerne bereit, das Kuchenproblem zu lösen.
Und als dritte Hand beim Zusammenbau bin ich auch ganz nützlich.
Und für die, die noch überlegen ob sie mitmachen: Auch beim Kuchen gibt es Prototypen, die vom Projektteam getestet werden müssen!

**Comment by rekna** [comment]
Ich schliesse mich Vi-ger mal an :-)

**Comment by YoungCatMike** [comment]
ich kann gerne beim Druck der Einzelteile unterstützen (software ist nicht meine stärke)

**Comment by miko007** [comment]
# 3D Druck
In diesem Thread möchte ich den Druck managen.

## Teile
* `.stl` Dateien, bitte [herunterladen][1] wenn am mitdrucken interessiert

## Verteilung
| Dateiname                              | Anzahl    | wird gedruckt von   | Drucker            | Material                   |
|:---------------------------------------|:---------:|:--------------------|:-------------------|---------------------------:|
| `GlaDOS Rotation Juction box V1.1.STL` | `x 1`     | @miko007            | Prusa i3 MK2.5s    | [PLA Weiß][pla_weiss]      |
| `Wireblock Large 1.stl` | `x1`| @YoungCatMike  | prusa Mini v1 | [PLA] [farbe unbestimmt, muss ich nachschauen|
| `Wireblock Large 2.stl` | `x1`| @YoungCatMike  | prusa Mini v1 | [PLA] [farbe unbestimmt, muss ich nachschauen|
| `Wireblock Small 1.stl` | `x1`| @YoungCatMike  | prusa Mini v1 | [PLA] [farbe unbestimmt, muss ich nachschauen|
| `Wireblock Small 2.stl` | `x1`| @YoungCatMike  | prusa Mini v1 | [PLA] [farbe unbestimmt, muss ich nachschauen|

[1]: https://github.com/maschinendeck/kanban/files/7258861/glados_lampe_teile_stl.zip

[pla_weiss]: https://www.dasfilament.de/filament-spulen/pla-1-75-mm/11/pla-filament-1-75-mm-weiss

**Comment by YoungCatMike** [comment]
@miko007 hast du auch eine liste mit der anzahl der benötigten teile? wenn ja pack sie einfach mit in den download ordner in die zip

**Comment by miko007** [comment]
> @miko007 hast du auch eine liste mit der anzahl der benötigten teile? wenn ja pack sie einfach mit in den download ordner in die zip

Ich werde die obige Tabelle vollständig ausfüllen. Die ist aktuell nur Platzhalter.
