### ISSUE TITLE
CNC Fräse fürs Maschinendeck

### ISSUE THREAD

**Issue by Eisfoehniks** [maschinendeck/kanban#4]
### Beschreibung
Ziel des Projektes ist die Auswahl, Einrichtung und Dokumentation einer CNC Fräse fürs Maschinendeck. Teil der Fräse soll ein Gehäuse zum Staubschutz sein. Gängige Sicherheitsvorkehrungen sollen erfüllt werden. Die Fräse sollte am Ende des Projektes nach einer kurzen Einweisung verwendbar sein.

### Weblinks
* Wiki Page coming soon...

### Tasks
- [x] Taskforce gründen
- [x] Präsentation für übrige Mitglieder erstellen 
- [x] Präsentation für übrige Mitglieder vortragen
- [x] Auswahl eines Konzeptes (Plenum)
- [ ] Projekt im Wiki anlegen
- [ ] Bestellung der Komponenten
- [ ] Kleinere Umbauten
- [ ] Konstruktion und Aufbau eines Gehäuses
- [ ] Inbetriebnahme CNC Fräse und Zubehör
- [ ] Dokumentation 
- [ ] Schritt für Schritt Anleitung und Schulungsunterlagen erstellen 
- [ ] Beispiele für einfache Projekte ins Wiki stellen

Das Budget wurde auf max. **`900,00€`** festgelegt. *(geschätzte Kosten aktuell `850,00€`)*

Ich suche mindestens **`2`** Mitstreiter.

### Bilder
![](https://wiki.maschinendeck.org/w/images/thumb/d/dd/Ava2.png/300px-Ava2.png)

[link1]: https://maschinendeck.org

**Comment by Eisfoehniks** [comment]
Aktueller Stand der Präsentation, Anmerkungen sind gerne erwünscht. Bei Bedarf kann ich ein Repo dafür aufmachen.
[Kauf einer Fräse fürs Deck.pptx](https://github.com/maschinendeck/kanban/files/7093262/Kauf.einer.Frase.furs.Deck.pptx)

**Comment by Eisfoehniks** [comment]
Präsentation wurde am 28.09. im Deck gehalten, hier nochmal die PDF Version:
[Kauf einer Fräse fürs Deck.pdf](https://github.com/maschinendeck/kanban/files/7247302/Kauf.einer.Frase.furs.Deck.pdf)
