### ISSUE TITLE
Netzwerk Modem/Router/AP

### ISSUE THREAD

**Issue by KoeterPK** [maschinendeck/kanban#5]
### Beschreibung
Das Netzwerk/WLAN besser machen um aktuelle ausfälle zu beseitigen.

### Tasks
- [x] Router für die Verwaltung unterschiedlicher Netzwerke einrichten (eventuell mit OpenWRT)
- [x] Provisorische AP's auf OpenWRT-Basis konfigurieren
- [x] Vodafone Router in Bridge-Modus versetzen und Router mit AP's in Betrieb nehmen

Das Budget wurde auf **`50,00€`** festgelegt. *(geschätzt auf `50,00€`)*
(für Router, neue AP's kommen eventuell später)

Ich suche mindestens **`1`** Mitstreiter.

### Hardware Vorschlag:
 - Router: [https://www.reichelt.de/hex-mit-dual-core-880-mhz-cpu-256-mb-ram-5x-gbit-lan-mtk-hex-p238779.html](https://www.reichelt.de/hex-mit-dual-core-880-mhz-cpu-256-mb-ram-5x-gbit-lan-mtk-hex-p238779.html)

[link1]: https://maschinendeck.org
