### ISSUE TITLE
Makerbot Replicator 2x

### ISSUE THREAD

**Issue by miko007** [maschinendeck/kanban#6]
### Beschreibung
Das Maschinendeck hat einen **Makerbot Replicator 2x** von Freunden des Vereins gespendet bekommen. Dieser ist hier und da etwas verbastelt und in die Jahre gekommen. Es gilt den Drucker wieder in einen Einsatzbereiten Zustand zu versetzen, damit er für Vereinsbelange herhalten kann, da er z.B. sehr gut für `ABS` Drucke geeignet ist.

### Weblinks
* [Herstellerseite][1]

### Tasks
- [ ] Grundsäuberung
- [ ] Keypad reparieren
- [ ] Hotend revamp
- [ ] Workflow zur Verwendung ausarbeiten
- [ ] Wikiseite anlegen
- [ ] Drucker PLA fähig machen
- [ ] Generelle Wartung *(Lager säubern und schmieren, Schrauben nachziehen etc.)*
- [ ] Standort festlegen

Das Budget wurde auf **`0,00€`** festgelegt. *(geschätzt auf `50,00€`)*

Ich suche mindestens **`1`** Mitstreiter.

### Bilder
![IMG_1104](https://user-images.githubusercontent.com/1271957/135754058-2ed09ed1-f2db-4fe5-ad37-e89200e5c9c2.JPG)

[1]: https://www.makerbot.gr/shop-makerbot-products/makerbot-replicator-2x-experimental-3d-printer/

**Comment by miko007** [comment]
Der Drucker wurde in seine Einzelteile zerlegt, das Projekt ist beendet.
